- id: remove-print-statements
  name: remove print statements
  description: remove all the print statements from your Python project
  entry: remove-print-statements
  language: python
  types: [python]
  require_serial: true
